DEVICE          : cuda               # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output_ablation/Bisenetv2/uavid2020'         # output folder name used for saving the model, logs and inference results

MODEL:
  NAME          : BiSeNetv2                                           # name of the model you are using
  BACKBONE      :                                                     # model variant
  PRETRAINED    : checkpoints/backbones/bisenetv2/bisenetv2.pth       # backbone model's weight

DATASET:
  NAME          : UAVid2020                    # dataset name to be trained
  ROOT          : 'data/UAVid2020'                # dataset root path
  IGNORE_LABEL  : 255
  H_FLIP        : true
  V_FLIP        : false

TRAIN:
  IMAGE_SIZE    : [1024, 1920]      # training image size in (h, w)
  BATCH_SIZE    : 4                 # batch size used to train
  EPOCHS        : 100               # number of epochs to train
  EVAL_INTERVAL : 10                 # evaluation interval during training
  AMP           : false             # use AMP in training
  DDP           : false             # use DDP training
  MAX_INERITER  : 999999            # max iteration for each epoch

LOSS:
  NAME          : CrossEntropy          # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.001           # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 5              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.01             # warmup ratio


EVAL:
  MODEL_PATH    : 'output/SOSNet_MobileNetV3-large_UAVid2020_best.pth'     # trained model file path
  IMAGE_SIZE    : [2160, 3840]                          # evaluation image size in (h, w)
  MSF:
    ENABLE      : false                               # multi-scale and flip evaluation
    FLIP        : true                                # use flip in evaluation
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]   # scales used in MSF evaluation
  TRAIN_SET     : false

TEST:
  MODEL_PATH    : 'output/SOSNet_MobileNetV3-large_UAVid2020_best.pth'     # trained model file path
  FILE          : 'data/UAVid2020/img_dir/test'                    # filename or foldername
  IMAGE_SIZE    : [2160, 3840]                          # inference image size in (h, w)
  OVERLAY       : false                                # save the overlay result (image_alpha+label_alpha)